### PR TITLE
rand_animation_CA

### PR DESCRIPTION
**Pull request by MFReaper**
Adding center_aligning to rand_animation function

### CODE REVIEW

**Comment by nerd-deus** [comment]
Tres bien. Works impressively. Tried with `\n' just for test, remains on the same line. Gets messy if the string passed is longer than the screen length.

**Comment by MFReaper** [comment]
Forgot to add for these cases. `\n` is a simple endl after every loop and the other thing can be made to work with the paragraph function. Will update and notify asap. Btw, I added you as a reviewer, so do you get a notification automatically

**Comment by nerd-deus** [comment]
yes, i do

**Comment by MFReaper** [comment]
All bugs fixed and requested features added ( @nerd-deus )

_for more details check commits_

**Comment by MFReaper** [comment]
__Do not forget to remove test code before merge__

**Comment by nerd-deus** [comment]
capture 1
capture
Check these two screenshots, i dunno what's wrong with Q

**Comment by nerd-deus** [comment]
capture
This is hella wierd, as soon as i add another letter to the message, something weird happens with the last line of the heading

**Comment by nerd-deus** [comment]
capture
definitely something wrong with the "Q"

**Comment by nerd-deus** [comment]
I tried different cases with "Q", works normally then why it show this error in this specific case, i don't understand.

**Comment by nerd-deus** [comment]
Dude, this error is strangest of all I've ever dealt with. I suppose its not the letter "Q" which causes it, but the letter"P" because i tested it with different set of letters and "P" always gave this strange error, i guess you should check it out. Probably some extra spacebar at the end of the letter output in lexicon. I'll test more and let you know.

**Comment by nerd-deus** [comment]
Runtime Error Log:-
	message: qwertyuiop
	outcome: base of all letters shifted to the right
	
	message: pqwertyuio
	outcome: only the base of letter "P" shifts to the right
	
	message: qpwertyuio, qwpertyuio, qweprtyuio, qwerptyuio and so on....
	outcome: base of the letters behind the letter "P" and including "P" itself shift to the right
	
	message: asdfghjklp
	outcome: perfect output with no shift in position of the base 
	
	message: pasdfghjkl
	outcome: base of all the letters ( excluding "P") shift to the left
	
	message:apsdfghjkl, aspdfghjkl, asdpfghjkl and so on....
	outcome: base of all the letters after "P" shift to the left
	
	message: zxcvbnmp
	outcome: base of all letters shift to the right
	
	message: pzxcvbnm
	outcome: only the base of letter "P" shifts to the right
	
	message: zpxcvbnm, zxpcvbnm, zxcpvbnm and so on....
	outcome: base of the letters behind the letter "P" and including "P" itself shift to the right
	
	"and so on" refers to all the possible messages while keeping position of all the letters constant and changing the position of the letter "P" one by one.

**Comment by MFReaper** [comment]
Thanks for telling this.
The problem was the lack of a space character in the design of P. Rest characters are fine.
complete the test with the latest rand_animation_CA branch

**Comment by nerd-deus** [comment]
The `rand_animation()` function is stable and does not show sign of any potential run time errors. The branch is ready to be merged into the master branch.

**Pull request merged**
